// <auto-generated />
namespace QLBH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_role));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031707101_add_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
